// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3Mi2yRfgNeL5mIfX23U-9dXuFu3Vxw0',
    appId: '1:782681184284:web:2280aaa186fe04fe2527d9',
    messagingSenderId: '782681184284',
    projectId: 'cookbook-895e3',
    authDomain: 'cookbook-895e3.firebaseapp.com',
    storageBucket: 'cookbook-895e3.appspot.com',
    measurementId: 'G-5BS8NJGMXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2Kt7IIxZsQ75xk6JO4_89NB27b3crvE',
    appId: '1:782681184284:android:b4c3aa140d873ae52527d9',
    messagingSenderId: '782681184284',
    projectId: 'cookbook-895e3',
    storageBucket: 'cookbook-895e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Jb56waOeJmUyATmKVO-At2oYxyn4IdE',
    appId: '1:782681184284:ios:4cc6fa553b6bd0612527d9',
    messagingSenderId: '782681184284',
    projectId: 'cookbook-895e3',
    storageBucket: 'cookbook-895e3.appspot.com',
    iosClientId: '782681184284-ujgn3nhisd4sdj8lda617cqqq4daltd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymAndFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Jb56waOeJmUyATmKVO-At2oYxyn4IdE',
    appId: '1:782681184284:ios:4cc6fa553b6bd0612527d9',
    messagingSenderId: '782681184284',
    projectId: 'cookbook-895e3',
    storageBucket: 'cookbook-895e3.appspot.com',
    iosClientId: '782681184284-ujgn3nhisd4sdj8lda617cqqq4daltd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymAndFoodApp',
  );
}
